import type { Metadata } from "next";
import Link from "next/link";
import { PageFrame } from "@/components/page-frame";
import { TrackedPlayLink } from "@/components/tracked-play-link";
import { getReleaseCards } from "@/lib/releases";
export const metadata: Metadata = { title: "Play", description: "Current ways to play or test Ratel Rage, with clear build status and platform information.", alternates: { canonical: "/play" }, openGraph: { title: "Play Ratel Rage", description: "The current browser prototype and honest Android playtest status.", images: ["/media/gameplay.webp"] }, twitter: { card: "summary_large_image", images: ["/media/gameplay.webp"] } };
export default function PlayPage() { const releases = getReleaseCards(); return <PageFrame kicker="PLAY RATEL RAGE" title="ENTER THE FIGHT." intro="Play the current desktop browser prototype locally. The Android build is still a debug playtest and is not ready for a public download.">
  <section className="content-section container"><div className="two-col">{releases.map(build=><article className="download-card" key={build.id}><p className="kicker">{build.number} / {build.platform}</p><h2>{build.title[0]}<br/><span>{build.title[1]}</span></h2><p>{build.description}</p><dl><div><dt>VERSION</dt><dd>{build.version}</dd></div><div><dt>FILE SIZE</dt><dd>{build.size}</dd></div><div><dt>RELEASE DATE</dt><dd>{build.releaseDate}</dd></div><div><dt>STATUS</dt><dd>{build.status}</dd></div></dl>{build.href?<TrackedPlayLink href={build.href}/>:build.id==="android"?<Link className="button button-ghost" href="/playtest">JOIN THE PLAYTEST →</Link>:<div className="form-message">A public play link will appear here after a distribution build is prepared.</div>}</article>)}</div></section>
  <section className="content-section panel-section"><div className="container"><p className="kicker">{"// "}AFTER THE FIGHT</p><h2>HELP SHAPE<br/><span>THE NEXT ROUND.</span></h2><div className="three-col"><Link className="info-card linked-card" href="/feedback"><h3>GIVE FEEDBACK ↗</h3><p>Tell us what felt great and what needs work.</p></Link><Link className="info-card linked-card" href="/bugs"><h3>REPORT A BUG ↗</h3><p>Give us the details that help reproduce a problem.</p></Link><Link className="info-card linked-card" href="/ideas"><h3>SUGGEST AN IDEA ↗</h3><p>Make a case for what should come next.</p></Link></div></div></section>
  </PageFrame>; }
