import Link from "next/link";
import { SiteHeader, SiteFooter } from "@/components/site-shell";

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero"><div className="hero-image" aria-hidden="true" /><div className="hero-vignette" aria-hidden="true" /><div className="container hero-content"><div className="eyebrow"><span className="status-light" /> NIGERIAN ARCADE BEAT ’EM UP <span className="eyebrow-rule" /> IN DEVELOPMENT</div><h1><span className="sr-only">Ratel Rage</span><img className="hero-logo" src="/media/logo.svg" alt="" /></h1><p className="hero-line">THE STREET HAS A PRICE.<br/><em>MAKE THEM PAY IT.</em></p><p className="hero-copy">Step into Darki’s fight through a pixel-built Lagos. Chain attacks, own the street, and take on the people running it.</p><div className="hero-actions"><Link className="button button-primary" href="/play">PLAY THE GAME <span aria-hidden="true">↗</span></Link><Link className="button button-ghost" href="/game">EXPLORE THE GAME <span aria-hidden="true">→</span></Link></div><div className="hero-meta"><span>01 / THE STREET TAX</span><span>DESKTOP BROWSER PROTOTYPE</span><span>ANDROID PLAYTEST IN VALIDATION</span></div></div><div className="hero-index" aria-hidden="true">PLAYER 01 <span>DARKI</span></div></section>
    <section className="ticker" aria-label="Game highlights"><div>PIXEL BUILT IN LAGOS <b>✦</b> STREET LEVEL COMBAT <b>✦</b> DARKI’S FIGHT <b>✦</b> PIXEL BUILT IN LAGOS <b>✦</b> STREET LEVEL COMBAT <b>✦</b></div></section>
    <section className="section gameplay-spotlight container" id="gameplay"><div className="section-heading"><p className="kicker">{"// "}THIS IS RATEL RAGE</p><h2>NO QUIET<br/><span>STREETS.</span></h2><p>A fast, hard hitting 2D brawler grounded in familiar streets and larger than life trouble.</p></div><div className="spotlight-art"><img src="/media/darki.webp" alt="Darki in a fighting stance" loading="lazy"/><span className="art-caption">DARKI // PLAYER 01</span></div><div className="spotlight-copy"><span className="chapter-num">01 — FIGHT YOUR WAY THROUGH</span><h3>HIT FIRST.<br/>HIT HARDER.</h3><p>Move between lanes, link attacks, block the return shot, and grab an opening. The fight keeps moving even when you don’t.</p><Link href="/game#combat" className="text-link">SEE HOW IT PLAYS <span>↗</span></Link></div></section>
    <section className="world-strip"><div className="container world-strip-inner"><div><p className="kicker">{"// "}THE WORLD</p><h2>LAGOS IS<br/>THE ARENA.</h2><p>Street corners, market heat, and a fight that starts with a demand you refuse to pay.</p><Link href="/game#world" className="button button-ghost">ENTER THE WORLD <span>↗</span></Link></div><img src="/media/street.webp" alt="Pixel art Lagos street environment from Ratel Rage" loading="lazy" /></div></section>
    <section className="section container roster-preview"><div className="section-top"><div><p className="kicker">{"// "}SELECT YOUR FIGHTER</p><h2>MEET THE <span>CREW.</span></h2></div><Link href="/game#characters" className="text-link">FULL ROSTER <span>↗</span></Link></div><div className="roster-grid"><article className="roster-card"><div className="roster-art"><img src="/media/darki.webp" alt="Darki" loading="lazy" /></div><div className="roster-label"><span>01 / PLAYER</span><h3>DARKI</h3></div></article><article className="roster-card"><div className="roster-art"><img src="/media/olodo.webp" alt="MC Olodo" loading="lazy" /></div><div className="roster-label"><span>02 / BOSS</span><h3>MC OLODO</h3></div></article><article className="roster-card"><div className="roster-art"><img src="/media/agbero.webp" alt="Senior Agbero enforcer" loading="lazy" /></div><div className="roster-label"><span>03 / ENFORCER</span><h3>AGBERO</h3></div></article></div></section>
    <section className="callout"><div className="container callout-inner"><div><p className="kicker">{"// "}BUILD THE FIGHT WITH US</p><h2>YOUR NEXT ROUND<br/><span>STARTS HERE.</span></h2><p>Play the current prototype, tell us what lands, and help shape what comes next.</p></div><div className="callout-actions"><Link href="/playtest" className="button button-primary">JOIN THE PLAYTEST <span>↗</span></Link><Link href="/updates" className="button button-ghost">DEVELOPMENT UPDATES <span>→</span></Link></div></div></section>
  </main><SiteFooter /></>;
}
