"use client";
import { useState } from "react";
import type { Idea } from "@/lib/ideas";
export function IdeasBoard({ initial, unavailable = false }: { initial: Idea[]; unavailable?: boolean }){
  const [ideas,setIdeas]=useState<Idea[]>(initial), [error,setError]=useState(unavailable?"Ideas are unavailable right now. Try again shortly.":""), [busy,setBusy]=useState("");
  async function refresh(){try{const response=await fetch("/api/ideas");const data=await response.json() as {ideas?:Idea[];error?:string};if(!response.ok)throw new Error(data.error||"Could not load ideas.");setIdeas(data.ideas||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load ideas.")}}
  async function vote(id:string){setBusy(id);try{const response=await fetch("/api/ideas/vote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ideaId:id})});const data=await response.json() as {error?:string;voted?:boolean};if(!response.ok)throw new Error(data.error||"Vote failed.");if(!data.voted){setError("You’ve already voted for that idea on this device.")}else{setError("");await refresh()}}catch(e){setError(e instanceof Error?e.message:"Vote failed.")}finally{setBusy("")}}
  return <div><p className="smallprint">Votes show interest from site visitors. They are one input into development decisions, not a representative poll.</p>{error&&<div className="form-message error" role="status">{error}</div>}{ideas.length===0?<div className="empty-state">No ideas posted yet. Start the conversation below.</div>:<div className="idea-grid">{ideas.map(idea=><article className="idea-card" key={idea.id}><div className="idea-top"><span className="badge">{idea.category.replaceAll("_"," ").toUpperCase()}</span><span>{idea.status.replaceAll("_"," ").toUpperCase()}</span></div><h3>{idea.title}</h3><p>{idea.description}</p><div className="idea-bottom"><small>BY {idea.name}</small><button type="button" onClick={()=>void vote(idea.id)} disabled={busy===idea.id} aria-label={`Vote for ${idea.title}`}>▲ {idea.votes} {busy===idea.id?"SAVING":"VOTES"}</button></div></article>)}</div>}</div>;
}
