import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const testers = sqliteTable("testers", { id: text("id").primaryKey(), displayName: text("display_name").notNull(), email: text("email").notNull(), device: text("device").notNull().default(""), os: text("os").notNull().default(""), source: text("source").notNull().default(""), consent: integer("consent").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t) => [uniqueIndex("testers_email_unique").on(t.email)]);
export const subscribers = sqliteTable("subscribers", { id: text("id").primaryKey(), email: text("email").notNull(), consent: integer("consent").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t) => [uniqueIndex("subscribers_email_unique").on(t.email)]);
export const feedback = sqliteTable("feedback", { id: text("id").primaryKey(), email: text("email"), rating: integer("rating").notNull(), enjoyed: text("enjoyed").notNull().default("[]"), improve: text("improve").notNull().default("[]"), comment: text("comment").notNull().default(""), version: text("version").notNull().default("browser prototype"), mediaKey: text("media_key"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const bugs = sqliteTable("bugs", { id: text("id").primaryKey(), email: text("email"), category: text("category").notNull(), description: text("description").notNull(), severity: text("severity").notNull(), version: text("version").notNull(), device: text("device").notNull().default(""), os: text("os").notNull().default(""), mediaKey: text("media_key"), status: text("status").notNull().default("open"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const ideas = sqliteTable("ideas", { id: text("id").primaryKey(), name: text("name").notNull().default("Player"), category: text("category").notNull(), title: text("title").notNull(), description: text("description").notNull(), status: text("status").notNull().default("suggested"), votes: integer("votes").notNull().default(0), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const ideaVotes = sqliteTable("idea_votes", { id: text("id").primaryKey(), ideaId: text("idea_id").notNull(), voter: text("voter").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t) => [uniqueIndex("idea_voter_unique").on(t.ideaId, t.voter)]);
export const events = sqliteTable("events", { id: text("id").primaryKey(), kind: text("kind").notNull(), page: text("page").notNull().default(""), platform: text("platform").notNull().default(""), version: text("version").notNull().default(""), source: text("source").notNull().default(""), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const rateLimits = sqliteTable("rate_limits", { key: text("key").primaryKey(), count: integer("count").notNull().default(0), expiresAt: text("expires_at").notNull() }, (t) => [index("rate_limits_expires_idx").on(t.expiresAt)]);
