import type { Metadata } from "next";
import Link from "next/link";
import { PageFrame } from "@/components/page-frame";
export const metadata: Metadata = { title: "The Game", description: "Meet Darki, MC Olodo, the Lagos street mission, and the real controls in Ratel Rage.", alternates: { canonical: "/game" }, openGraph: { title: "Ratel Rage — The Game", description: "Darki, the Lagos street mission, and real arcade combat.", images: ["/media/gameplay.webp"] }, twitter: { card: "summary_large_image", images: ["/media/gameplay.webp"] } };

const controls = [
  ["MOVE", "A / D", "Move left and right"], ["CHANGE LANE", "W / S", "Move up and down the street"],
  ["JUMP", "SPACE", "Clear an attack or close a gap"], ["JAB / CHAIN", "J / LEFT CLICK", "Start and link attacks"],
  ["UPPERCUT", "K", "Land a heavy hit"], ["KICK", "RIGHT CLICK", "Strike with your feet"],
  ["GRAB", "G / MIDDLE CLICK", "Catch an opponent in range"], ["BLOCK", "HOLD L / SHIFT", "Hold your guard"],
  ["EXECUTION", "E", "Use when available"], ["PAUSE", "P", "Pause the fight"],
];

export default function GamePage() { return <PageFrame kicker="THE GAME" title="FIGHT FOR THE STREET." intro="A Nigerian-inspired 2D arcade brawler. One developed street mission is playable in the current browser prototype; the wider case is still being built.">
  <section className="content-section container" id="combat"><div className="section-top"><div><p className="kicker">{"// "}ACTUAL GAMEPLAY</p><h2>TAKE YOUR<br/><span>SPACE.</span></h2></div><span className="badge">CURRENT PROTOTYPE</span></div><div className="gameplay-photo"><img src="/media/gameplay.webp" alt="Actual Ratel Rage browser gameplay: Darki on a Lagos street with the in-game health and rage HUD"/><span>CAPTURED FROM THE RUNNING BROWSER BUILD · LEVEL 01</span></div><div className="three-col" style={{marginTop:22}}><article className="info-card"><p className="kicker">01 / MOVE</p><h3>WORK THE LANES.</h3><p>Move left and right, step into a different lane, and choose where the next clash happens.</p></article><article className="info-card"><p className="kicker">02 / ATTACK</p><h3>CHAIN THE HITS.</h3><p>Jabs, an uppercut, kicks, grabs, and a rush give you more than one way through a crowd.</p></article><article className="info-card"><p className="kicker">03 / SURVIVE</p><h3>KEEP YOUR GUARD.</h3><p>Block the return shot, read the mob, and watch for the boss’s reinforcements.</p></article></div></section>
  <section className="content-section panel-section" id="characters"><div className="container"><p className="kicker">{"// "}THE ROSTER</p><h2>THE PEOPLE IN<br/><span>YOUR WAY.</span></h2><div className="character-list"><article><div className="character-art"><img src="/media/darki.webp" alt="Darki sprite"/></div><div><span className="badge">PLAYER CHARACTER</span><h3>DARKI</h3><p>Street investigator. When MC Olodo’s crew demands its cut, Darki refuses. He follows the trouble further than the street corner.</p><p className="muted">Fighting style: close-range brawling, chained strikes, grabs, and defense.</p></div></article><article><div className="character-art"><img src="/media/olodo.webp" alt="MC Olodo sprite"/></div><div><span className="badge">LEVEL 01 BOSS</span><h3>MC OLODO</h3><p>A fictional motor park chairman collecting a “street tax” from drivers and traders. His enforcers make sure the demand is heard.</p><p className="muted">Encounter: a boss fight with retreat, reinforcements, and an enraged phase.</p></div></article><article><div className="character-art"><img src="/media/agbero.webp" alt="Senior Agbero enforcer sprite"/></div><div><span className="badge">ENFORCER</span><h3>AGBERO CREW</h3><p>Olodo’s street muscle. Standard enforcers and senior reinforcements keep Darki from reaching the boss.</p></div></article></div></div></section>
  <section className="content-section container" id="world"><p className="kicker">{"// "}LEVEL 01 — THE STREET TAX</p><h2>LAGOS ISLAND.<br/><span>BALOGUN STREET.</span></h2><div className="two-col world-detail"><div><p>Danfo and keke traffic. Traders at work. A street tax enforced by Olodo’s crew. Darki steps in, says no, and the fight begins.</p><p className="muted">The next case points toward Commissioner Masood Jibril and a hidden Cabal. Distinct Level 02 combat and story content are still in development.</p><Link className="button button-primary" href="/play">PLAY THE CURRENT MISSION ↗</Link></div><div className="art-frame"><img src="/media/story.webp" alt="Darki on a Lagos street in Ratel Rage story art" loading="lazy" /></div></div></section>
  <section className="content-section panel-section" id="controls"><div className="container"><p className="kicker">{"// "}HOW TO PLAY</p><h2>KNOW YOUR<br/><span>BUTTONS.</span></h2><p className="muted">Desktop browser controls from the current build. Mobile touch controls are being tuned in the Android playtest build.</p><div className="controls-grid">{controls.map(([name,key,desc]) => <div className="control-row" key={name}><b>{name}</b><kbd>{key}</kbd><span>{desc}</span></div>)}</div><div className="form-message">On Android, the debug build uses a movable virtual stick with Jump, Block, Kick, Jab, Grab, and pause controls. That build still needs phone validation and release signing.</div></div></section>
  <section className="content-section container"><p className="kicker">{"// "}WHY WE’RE MAKING IT</p><h2>FROM STREETS<br/><span>WE RECOGNIZE.</span></h2><div className="two-col"><p className="lead">Ratel Rage takes the urgency of classic arcade brawlers and grounds it in a Nigerian street scene that feels lived in.</p><p>The Lagos setting is part of the fight: the traffic, the buildings, the people watching, and the power structures behind the first confrontation. We’re building the game in public through prototypes and playtests, then using player feedback to sharpen the combat and the next case.</p></div></section>
  </PageFrame>; }
